name: conda_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - kagglehub
      - jupyter 
      - ipykernel
      - pandas
      - numpy
      - plotly
      - Pillow
      - matplotlib
      - opencv-python-headless
      - scikit-learn
      - albumentations
      - scikit-image
      - imbalanced-learn
      - seaborn
      - torchvision
      - shap
      - joblib
      - "-e ."
